/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/b4d28d53-2a41-4cbb-a8fc-1e625cc7d308 
  Arduino IoT Cloud Variables description
  The following variables are automatically generated and updated when changes are made to the Thing

  CloudIlluminance intensity;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
float sensor;
#include <Arduino.h>
#include <hp_BH1750.h>
hp_BH1750 BH1750;



void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  pinMode(LED_BUILTIN, OUTPUT);
  
  bool avail = BH1750.begin(BH1750_TO_GROUND);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  BH1750.start();
  sensor = BH1750.getLux();
  light_sensor = sensor
  if(light_sensor > 800)
  {
     Serial.println("light detected");
     digitalWrite(LED_BUILTIN, HIGH);
     delay(300);
  }
  
}
void onIntensityChange(){
  // Add your code here to act upon Intensity change
}
